### PR TITLE
switch to chronos metrics, remove insecure

### PR DESCRIPTION
**Pull request by arnetheduck**
See https://github.com/status-im/nimbus-eth2/pull/2468

also fixes pcre linking for real, and adds some random build flags that
help nimbus-eth2 stay afloat

### CODE REVIEW

**Review by stefantalpalaru — APPROVED** [review]

**Comment by stefantalpalaru** [comment]
The Windows ICE is probably triggered by `-fno-omit-frame-pointer`:

https://sourceforge.net/p/mingw-w64/bugs/880/

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86593

**Comment by arnetheduck** [comment]
> The Windows ICE is probably triggered by -fno-omit-frame-pointer:

odd, any idea why `nimbus-eth2` doesn't trigger it?

**Comment by stefantalpalaru** [comment]
I'm thinking there's some mitigating factor, like LTO.

**Comment by tersec** [comment]
Is there a reason the CIs still use a version of mingw-w64 which has this problem, as opposed to one which according to those two links doesn't, such as a mingw-w64 with gcc 9.x? For example, https://packages.ubuntu.com/focal/mingw-w64 from 20.04 LTS has gcc 9.3.

This doesn't seem like an end-user build configuration necessarily worth supporting or working around at this point.

**Comment by stefantalpalaru** [comment]
Ah, the nimbus-eth2 solution was to downgrade MinGW-w64 to 6.3.0: https://github.com/status-im/nimbus-eth2/blob/8391d3f83e43e7e6d13b6bd716f06510e6ffd05c/.github/workflows/ci.yml#L182

**Pull request merged**
