### PR TITLE
use Nim 2.0.6

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by jangko** [comment]
A really weird error from fluffy CI.

```
D:\a\nimbus-eth1\nimbus-eth1\fluffy\network\history\beacon_chain_block_proof_bellatrix.nim(113, 9) template/generic instantiation of `build_proof` from here
D:\a\nimbus-eth1\nimbus-eth1\vendor\nim-ssz-serialization\ssz_serialization\proofs.nim(308, 17) template/generic instantiation of `hash_tree_root` from here
D:\a\nimbus-eth1\nimbus-eth1\vendor\nim-ssz-serialization\ssz_serialization\merkleization.nim(1467, 25) template/generic instantiation of `hash_tree_root_multi` from here
D:\a\nimbus-eth1\nimbus-eth1\vendor\nim-ssz-serialization\ssz_serialization\merkleization.nim(1379, 22) template/generic instantiation of `hashTreeRootAux` from here
D:\a\nimbus-eth1\nimbus-eth1\vendor\nim-ssz-serialization\ssz_serialization\merkleization.nim(1061, 6) template/generic instantiation of `enumerateSubFields` from here
D:\a\nimbus-eth1\nimbus-eth1\vendor\nim-ssz-serialization\ssz_serialization\merkleization.nim(1099, 35) template/generic instantiation of `hash_tree_root_multi` from here
D:\a\nimbus-eth1\nimbus-eth1\vendor\nim-ssz-serialization\ssz_serialization\merkleization.nim(1379, 22) template/generic instantiation of `hashTreeRootAux` from here
D:\a\nimbus-eth1\nimbus-eth1\vendor\nim-ssz-serialization\ssz_serialization\merkleization.nim(940, 37) Error: type mismatch
Expression: `[]`(x, chunk)
  [1] x: array[0..8191, Eth2Digest]
  [2] chunk: Limit

Expected one of (first mismatch at [position]):
[0] func `[]`(s: BitSeq; pos: Natural): bool
[0] func `[]`(v: ForkDigest | Version | DomainType; idx: int): byte
[0] proc `[]`(s: string; i: BackwardsIndex): char
[0] proc `[]`(s: var string; i: BackwardsIndex): var char
[0] proc `[]`[A, B](t: OrderedTableRef[A, B]; key: A): var B
[0] proc `[]`[A, B](t: OrderedTable[A, B]; key: A): lent B
[0] proc `[]`[A, B](t: TableRef[A, B]; key: A): var B
[0] proc `[]`[A, B](t: Table[A, B]; key: A): lent B
[0] proc `[]`[A, B](t: var OrderedTable[A, B]; key: A): var B
[0] proc `[]`[A, B](t: var Table[A, B]; key: A): var B
[0] proc `[]`[A](s: var HashSet[A]; key: A): var A
[0] proc `[]`[A](t: CountTableRef[A]; key: A): int
[0] proc `[]`[A](t: CountTable[A]; key: A): int
[0] proc `[]`[I: Ordinal; T](a: T; i: I): T
[0] proc `[]`[Idx, T; U, V: Ordinal](a: array[Idx, T]; x: HSlice[U, V]): seq[T]
[0] proc `[]`[Idx, T](a: array[Idx, T]; i: BackwardsIndex): T
[0] proc `[]`[Idx, T](a: var array[Idx, T]; i: BackwardsIndex): var T
[0] proc `[]`[T, U: Ordinal](s: string; x: HSlice[T, U]): string
[0] proc `[]`[T; U, V: Ordinal](s: openArray[T]; x: HSlice[U, V]): seq[T]
[0] proc `[]`[T](s: openArray[T]; i: BackwardsIndex): T
[0] proc `[]`[T](s: var openArray[T]; i: BackwardsIndex): var T
[0] template `[]`(a: BitArray; pos: Natural): bool
[0] template `[]`(a: auto; i: SyncSubcommitteeIndex): auto
[0] template `[]`(arr: array[SYNC_COMMITTEE_SIZE, auto] | seq;
              idx: IndexInSyncCommittee): auto
[0] template `[]`(epochFlags: EpochParticipationFlags;
              idx: ValidatorIndex | uint64 | int): ParticipationFlags
[0] template `[]`(s: string; i: int): char
[0] template `[]`(x: BitList; idx: auto): auto
[0] template `[]`(x: HashList | HashArray; idx: auto): auto
[0] template `[]`(x: List; idx: auto): untyped
[0] template `[]`(x: var HashArray; idx: auto): auto
[0] template `[]`(x: var HashList; idx: auto): auto
[0] template `[]`[E](self: Result[void, E])
[0] template `[]`[T: not void; E](self: Result[T, E]): T
[0] template `[]`[T](a: seq[T]; b: ValidatorIndex): auto
```

When I add this template before `buildProof`, it can compile. But this workaround should not necessary:

```Nim
# `Limit` is an alias to int64
template `[]`(x: openArray[Eth2Digest], chunk: Limit): Eth2Digest =
  x[chunk]
```

https://github.com/status-im/nimbus-eth1/blob/e3d14bd9210683cf84af4119886560b852614154/fluffy/network/history/beacon_chain_block_proof_bellatrix.nim#L106

**Comment by narimiran** [comment]
> ```
> (...)
> vendor\nim-ssz-serialization\ssz_serialization\proofs.nim
> vendor\nim-ssz-serialization\ssz_serialization\merkleization.nim
> (...)
> ```

From what I can tell, `nimbus-eth1` is using a 3 month old version of `nim-ssz-serialization`. Does it maybe help if you run it with a newer version of `nim-ssz-serialization`?

**Comment by jangko** [comment]
When I use the latest nim-ssz-serialization, the above error still there.

**Comment by narimiran** [comment]
> `# `Limit` is an alias to int64`

I'm trying to make a simple(r) self-contained example on my machine.

I couldn't find where exactly `Limit` is defined, but:
- if it is defined as `Limit = int64`, then there is no problem in my code.
- on the other hand, if it is defined as `Limit = distinct int64`, then I can reproduce the error above.

**Comment by tersec** [comment]
Yes, Nim 2.0 requires arrays to be indexed by the same type they're declared with.

This doesn't appear to be a bug, but a design change, but not sure. In any case, aligning the types isn't really a workaround.

**Comment by jangko** [comment]
Yup, The array is defined with uint64 index.

https://github.com/status-im/nimbus-eth2/blob/d2a07514541ffe6ee02a2ec7272ce7a315131e04/beacon_chain/spec/datatypes/base.nim#L340

https://github.com/status-im/nimbus-eth2/blob/d2a07514541ffe6ee02a2ec7272ce7a315131e04/beacon_chain/spec/presets/mainnet/phase0_preset.nim#L54

I think we cannot avoid using the `[]` template workaround.

**Comment by tersec** [comment]
And thus a simple repro:
```nim
type B = int64
var x: array[8192'u64, bool]
discard x[B(0)]
```
runs in Nim 1.6, not Nim 2.0.

**Comment by tersec** [comment]
It looks like that https://github.com/status-im/nimbus-eth1/pull/2384/commits/42feb8f574b3170e92c69e63a1ffbf440cfc7c6d template is just recursively calling itself and never converts to `uint64`?

**Review by tersec — APPROVED** [review]

**Pull request merged**
